[package]
name = "multi-target"
version = "0.1.0"
authors = ["John Doe <example@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
